### ISSUE TITLE
bug sur log

### ISSUE THREAD

**Issue by Egainmoney** [sebcaps/atmofrance#6]
`Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:595
Integration: Capteur (documentation, issues)
First occurred: 19:44:48 (12 occurrences)
Last logged: 19:44:49

Error adding entities for domain sensor with platform atmofrance
Error while setting up atmofrance platform for sensor
atmofrance: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 591, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 595, in state
    raise ValueError(
ValueError: Sensor sensor.ozone_montbeton has device class 'aqi', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '' (<class 'str'>)
`

apres plusieurs test de code regional  je vois queue la region occitanie pose problem ? aucune des station ne remote de l'API 
problem Atmo ?

**Comment by sebcaps** [comment]
Bonjour,
  Concernant l'erreur je pense qu'elle apparait lors du rafraichissement des données alors qu'il n'y a pas de donnée à traiter, c'est certes un bug et je vais voir pour le  corriger.
Concernant l'absence de donnée de manière globale à l'échelle de la région Occitanie c'est assez étonnant mais :
- pas improbable
- je ne peux rien y faire ;-). 
Le composant se base sur les données fournies, sans données difficile de faire qqchose.

**Comment by Egainmoney** [comment]
salut je vais voir si ont peut pas les contacter pour voir si il peuvent corriger le bug mais y bien aucun retour sur les départements de l'occitanie j'ai tester une 15 de villes je suis dégoutés ;)

**Comment by Egainmoney** [comment]
Salut je vais voir si on ne peut pas les contacter pour voir s'ils peuvent corriger le bug je vois bien que dans ma région j'ai très peu d'indice sur la carte alors que les autres regions sont pleine de données. Y a bien aucun retour sur les départements de l'Occitanie j'ai testé une 15 de villes je suis dégouté ;)
tu as deja eut des conctact avec eux ?

**Comment by sebcaps** [comment]
Ca ne coute pas grd chose de leur écrire/demander.
De mon coté un seul contact pour savoir si je pouvais utiliser le logo et une réponse (positive) dans un délai vraiment raisonnable :-)
Leur site permet  de leur écrire.

**Comment by Egainmoney** [comment]
Ok demande faite je te tiens au courant de leur réponse

**Comment by sebcaps** [comment]
Gestion des données au niveau EPCI (communauté de commune) pris en compte dans la nouvelle version
