### ISSUE TITLE
Le code INSEE n'est pas forcément celui de la commune, mais peut être celui de l'ECPI

### ISSUE THREAD

**Issue by lbaey** [sebcaps/atmofrance#9]
Pour la Bretagne, AirBreizh fourni des données à l'échelle des communautés de communes.
Par exemple, pour Rennes, le code INSEE à mettre dans le `code_zone` du filtre n'est pas celui de la commune, mais celui de lECPI "Rennes Métropole":
```
{'type': 'FeatureCollection', 'name': 'national_data.national_ind_atmo', 'crs': {'type': 'name', 'properties': {'name': 'urn:ogc:def:crs:EPSG::3857'}}, 'features': [{'type': 'Feature', 'properties': {'gml_id': 719139404, 'aasqa': '53', 'date_maj': '2023/12/18 14:32:34.817+01', 'partition_field': '532023w51', 'code_no2': 0, 'code_o3': 0, 'code_pm10': 0, 'code_pm25': 0, 'code_qual': 2, 'code_so2': 0, 'code_zone': '243500139', 'coul_qual': '#50CCAA', 'date_dif': '2023/12/18', 'date_ech': '2023-12-19', 'epsg_reg': '2154', 'lib_qual': 'Moyen', 'lib_zone': 'Rennes Métropole', 'source': 'Air Breizh', 'type_zone': 'EPCI', 'x_reg': 349555.007045374, 'x_wgs84': -1.71146933693149, 'y_reg': 6789093.38652832, 'y_wgs84': 48.1081581756375}, 'geometry': None}]}
```
J'ai obtenu des données en changeant le code INSEE directement dans les fichiers de configuration de HA, mais il serait intéressant d'avoir une option pour saisir directement son code INSEE dans le ConfigFlow, sans passer par le code postal et l'API de INSEE.

**Comment by sebcaps** [comment]
Merci pour le retour.
En toute franchise, le code postal est au quotidien plus utilisé que le code INSEE, mais pourquoi pas.
Si le temps me le permet, j'envisagerai cette option dans le config flow, si le coeur t'en dit, les PR sont bienvenues.

**Comment by mrstilt** [comment]
Le problème s'applique aussi à l'Occitanie, pour laquelle les données d'AtmoFrance sont regroupées par communauté de communes (EPCI) et rattachée au code INSEE de la communauté de communes, qui est d'un format différent du code INSEE d'une commune (11 chiffres au lieu de 5). Les communautés de communes n'ayant pas de code postal propre, impossible de faire le lien entre le code postal du domicile et le code INSEE de l'EPCI utilisé par AtmoFrance, ainsi aucune donnée ne remonte dans l'intégration.

Comme le propose [lbaey](https://github.com/lbaey), il faudrait avoir la possibilité de saisir directement le code INSEE de l'EPCI concerné au lieu du code postal pour la Bretagne et l'Occitanie (voire d'autres régions concernées ?). 

Désolé mais je n'ai pas la compétence pour proposer un PR. En tout cas merci pour le temps passé à développer cette intégration.

**Comment by sebcaps** [comment]
@lbaey , @mrstilt 
  Prise en compte de l'EPCI dans la version 1.0.5.
  Rien a faire, sur saisie du code postal, integration determine le niveau (commune ou EPCI) auquel les données sont dispo.
  N'hésitez pas en cas de soucis..
